### ISSUE TITLE
something about the dataset

### ISSUE THREAD

**Issue by gengrz123** [xmeng525/RealTimeDenoisingNeuralBilateralGrid#1]
I encounter a problem when I run network_train.py. I cannot find depth_path and noisy_path. Where could I obtain these files?
![11](https://user-images.githubusercontent.com/26324318/88159132-7b307280-cc3f-11ea-9ca2-342bc0865122.PNG)

**Comment by xmeng525** [comment]
Thank you for pointing it out!
The dataset of depth & noisy has been uploaded. Please download it from:
https://www.dropbox.com/sh/qrf9mwofvy8ikan/AACMvXs_7W2nEk5LpiT1TSHca?dl=0
Please let me know if you have other questions!
