### ISSUE TITLE
How to generate temporal-accumulated data?

### ISSUE THREAD

**Issue by lyclyc171** [xmeng525/RealTimeDenoisingNeuralBilateralGrid#10]
Hi, I wanna implement BilateralGrid to denoise renderred result made by my own engine which works on volume rendering, but unfortunately this engine  can't output temporal accmulated radiance because it doesn't have this feature. We have read the paper of [SKW∗17] and [KIM∗19] but it's too complicated to make a quick output. So we want to output radiance of each frame and accumulate them.  Do you have any suggestion (links or codes) ? How do you deal with this problem?

**Comment by xmeng525** [comment]
Hi, you may want to checkout the temporal accumulation of BMFR:
https://github.com/maZZZu/bmfr/blob/4b821c6efcf7813c774ffc0d4891b9603f1c911f/opencl/bmfr.cl#L290
Good luck!

**Comment by lyclyc171** [comment]
thanks a lot! looking forward your great work in the future!

**Comment by xmeng525** [comment]
Resolved
