### ISSUE TITLE
Question about albedo

### ISSUE THREAD

**Issue by deadmarston** [xmeng525/RealTimeDenoisingNeuralBilateralGrid#2]
Hello there,

Thanks for your great work and for sharing your code!

I hold a question about albedo generation. If I understand correctly, albedo should be "brdf * cos / pdf" at the first surface intersection point, which would be a bit noisy under the 1spp path tracing, especially for the glossy material. But in the dataset of BMFR, the albedo is relatively clear. Could you tell me how to generate clear albedo under the 1spp path tracing?

Thanks for reading and I am looking forward to your answer:)

Cheer!

**Comment by xmeng525** [comment]
Hi,
The BMFR dataset was rendered with [Baikai](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal). I haven't had a chance to run the engine by myself, but I agree with you that the 1-spp albedo should not be a super clear image. I used the clear albedo from the BMFR dataset in my Denoiser for a fair comparison with the state-of-the-art.
Comparing "the image denoised with a 1-spp albedo" and "the image denoised with a clear albedo" will be left for future work. Please let me know if you have finished any similar comparisons!

**Comment by deadmarston** [comment]
Hi there,

Thanks for your reply. I checked the source code of Baikai and it seems that they only record the diffuse color from the material, which makes sense for a perfect Lambertian brdf. I haven't tried such experiments to compare the "1-spp albedo" and "clear albedo" so far, and once I have tried that I will leave a comment here.

Again, thanks for your reply.

**Comment by lyclyc171** [comment]
> Hi there,
> 
> Thanks for your reply. I checked the source code of Baikai and it seems that they only record the diffuse color from the material, which makes sense for a perfect Lambertian brdf. I haven't tried such experiments to compare the "1-spp albedo" and "clear albedo" so far, and once I have tried that I will leave a comment here.
> 
> Again, thanks for your reply.

Hi, Have you tried any experiments for this comparison? I have the same problem now that generate some noisy features
