### ISSUE TITLE
Question about result image folder in Dropbox

### ISSUE THREAD

**Issue by ChampagneBoom** [xmeng525/RealTimeDenoisingNeuralBilateralGrid#5]
Hello there:

It seems result_BMFR_dataset/sponza/MRKP-5-layer(w_albedo_demod) folder stores 'classroom' scene results but not 'sponza' scene (https://www.dropbox.com/sh/ar7g0lisb2ljlh6/AAAUHLObj7iPMODKo0YWf9hPa/sponza/MRKP-5-layer(w_albedo_demod)?dl=0&subfolder_nav_tracking=1). Would you mind updating it?

Thanks for sharing your outstanding work :)

**Comment by xmeng525** [comment]
Hi,
Thank you for pointing it out! I have lost access to the original data, but I just rerun the training experiment and uploaded the new version. Please click the link again and let me know if you have access to the new result.
The evaluation of the new result is slightly different from the evaluation of the original version, for the new result:
Scene: sponza
psnr=30.5926
ssim=0.9636
rmse=0.0300
smape=5.3838
rltv_mse=0.8881

**Comment by ChampagneBoom** [comment]
Yes, I can get the new results. Thanks for updating.
