### ISSUE TITLE
Question about Tungsten dataset

### ISSUE THREAD

**Issue by ChampagneBoom** [xmeng525/RealTimeDenoisingNeuralBilateralGrid#6]
Hello there,
Would you mind releasing your temporal accumulated color image of Tungsten dataset, just like the BMFR dataset https://www.dropbox.com/sh/qrf9mwofvy8ikan/AACMvXs_7W2nEk5LpiT1TSHca?dl=0? Because the hyper-parameters you used in temporal accumulation operation for Tungsten scenes is not known. It will be good if you release the accumulated dataset.
Thanks!

**Comment by xmeng525** [comment]
Hi,
As I said in the paper, the Tungsten dataset rendered at 64-spp does not use temporal accumulation as a pre-process. I don't have the accumulated color image of Tungsten dataset.
The repo I used for generating the accumulated color image is: https://github.com/maZZZu/bmfr. You can generate the accumulated dataset with the code. The camera information required for the accumulation process (the "camera position" and "lookat" vectors) could be found in https://github.com/xmeng525/TungstenFlythrough)
I can help in this part. Please email me if you would like to collaborate.

**Comment by ChampagneBoom** [comment]
Sorry, I missed that part when reading the paper. Thanks for your patient explaining

**Comment by ChampagneBoom** [comment]
Hi, there missed bathroom2 scene in https://www.dropbox.com/sh/54fa7cv4k3847b0/AAAEGAGxEx_TW0lGlcmmoqlua?dl=0. Would you mind updating it？

**Comment by xmeng525** [comment]
Hi, I didn't generate the bathroom2 dataset.

**Comment by ChampagneBoom** [comment]
Hi, your paper says "Our dataset includes rendered images at a resolution of 1280×720 from nine scenes" and top left  scene in Figure3 seems "bathroom" scene, and your another project https://github.com/xmeng525/TungstenFlythrough includes a "bathroom" json. maybe this misslead me. So actually you used eight scenes totally and there is a "staircase" scene instead of "bathroom" scene?

**Comment by xmeng525** [comment]
Hi,
We generated the json files for the bathroom scene and we did generate the rendered images using Tungsten.
However, the scene is limited in area and complexity. We only generated 20 viewpoints for the bathroom and images we got from the 20 viewpoints are very similar. We decided not to include the bathroom scene in the training process. And I no longer have the images for this scene on my side.

**Comment by ChampagneBoom** [comment]
I am clear now, thank you very much!
